export const COORDINATS_FETCH_REQUESTED = 'COORDINATS_FETCH_REQUESTED'
export const COORDINATS_FETCH_SUCCEEDED = 'COORDINATS_FETCH_SUCCEEDED'
export const COORDINATS_FETCH_FAILED = 'COORDINATS_FETCH_FAILED'